### ISSUE TITLE
1.1-24^H^H^H^H1.1-25 release checklist

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#596]
CRAN is asking for an update by October 20

We should think about what changes we want to push in this release.

- [ ] speed up tests

Overall checking is currently taking about 23 minutes on CRAN Windows machines, so we need to reduce test/example timing by *more than 50%*. I guess I will implement this by making a whole bunch of the tests conditional on `LME4_TEST_LEVEL > 1` ...

- [x] troubleshoot/resolve [vignette compaction issues](https://stat.ethz.ch/pipermail/r-package-devel/2020q4/006086.html)
- [x]  replace or remove dependency on HSAUR

From an e-mail (20 Sep) titled "CRAN packages depending on HSAUR/HSAUR2":

> Those HSAUR packages were superseded in 2014: please migrate to HSAUR3 before Oct 20 to safely retain your package on CRAN. 

It's not at all clear to me where this information comes from: I can't find it anywhere on the web, I guess the package authors communicated with CRAN directly?? 

This is already updated, but maybe it would be better to remove the (weak) dependency entirely: the *only* use of `HSAUR*` is for the "toenail" data from de Backer et al 1998.  We could just grab these data ourselves.

- [x] troubleshoot/check reverse dependency machinery; check reverse dependencies; 

We [ran into trouble on submission on the last release](https://github.com/lme4/lme4/issues/562) because my RD pipeline (which is based on the `revdepcheck` package) failed because packages that won't install (or whose dependencies won't), or error out with the old version because of system dependencies, don't get reported ...)

After much command line bullshittery these are the packages (out of 347) I haven't been able to check ...

| pkg       |  issues |
| ---------- | --------- |
| diffcyt | need flowCore; FlowSOM; HDCytoData; CATALYST; flowCore install fails |
| huxtable |  error on CRAN | 
| IVAS |  PNG/X11 problem |
| LMERConvenienceFunctions |  JPEG/X11 problem |
| lmSupport |  TIFF/X11 problem |
| psych     |  PNG/X11 problem |
| splatter |  ???? |

(`ctsem`, `glmulti`, `OpenMX`, `rstanarm`, `rstap` only run on head node of my test system because of compiler etc. compatibility issues ...)

- [x] `simulate.formula` compatibility

Resolve #566

- [x] bits and pieces

resolve #556, #551, others? #526?

- [x] resolve [UBSAN issues](https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/lme4/) ?
    - puzzled what's up with this. Something like this was fixed in 961696f5b8d (28 March), but that was *before* the current CRAN release. The error is `optimizer.h:22:11: runtime error: load of value 176, which is not a valid value for type 'bool'`, which looks like an uninitialized boolean.  
    - I just found another possibility and fixed it in f839f2f81c (although this doesn't seem to be anywhere near the reported location of the problem??)
    - checking 1.1-23 tarball from CRAN vs. current tarball, looks like this is OK now.
