### ISSUE TITLE
1.1-28 release checklist

### ISSUE THREAD

**Issue by bbolker** [lme4/lme4#655]
We're asked to upload a new release because new R checks have identified some small bugs in tests.  (Deadline, 6 Feb 2022).

## building/testing

- [x] reverse-dependency checks
- [x] checks on win-builder, r-hub, etc etc
- [x] don't forget to build tarball with `R CMD build --compact-vignettes=both lme4`

## bug fixes

- [x] low-hanging fruit: #645, #652

... and more as time allows ...

**Comment by bbolker** [comment]
OK, trying to resurrect my reverse-dependency-checking pipeline now. (I think the changes to this version are very small, but they're not completely trivial, and I've been bitten before ...)

**Comment by bbolker** [comment]
submitted, pretests passed, reverse dependency checks failed for `glmmTMB` in a way that looks like it must be a false positive ... responded to CRAN Thu, Feb 3, 10:10 AM (Toronto time), waiting for their response. If we have a chance maybe we can sneak in the fix for #658 ...

**Comment by bbolker** [comment]
on the way to CRAN now.
